##
## Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
##
## NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
## property and proprietary rights in and to this material, related
## documentation and any modifications thereto. Any use, reproduction,
## disclosure or distribution of this material and related documentation
## without an express license agreement from NVIDIA CORPORATION or
## its affiliates is strictly prohibited.
##

robot_cfg:
  kinematics:
    use_usd_kinematics: False
    urdf_path: "robot/ur_shadow_hand/bimanual_srhand_ur.urdf"
    asset_root_path: "robot/ur_shadow_hand"
    #isaac_usd_path: "/Isaac/Robots/UR10/ur10_long_suction.usd"
    usd_robot_root: "/ur10"
    usd_path: "robot/ur_shadow_hand/bimanual_srhand_ur.usd"
    base_link: "world"
    ee_link: "rh_forearm" #"tool0"
    link_names: ["lh_forearm"] # ['palm', 'thdistal', 'lfdistal', 'rfdistal', 'mfdistal', 'ffdistal']
    collision_link_names: ['ra_shoulder_link','ra_upper_arm_link', 'ra_forearm_link', 'ra_wrist_1_link', 'ra_wrist_2_link' ,'ra_wrist_3_link',
    "rh_forearm",
    #"rh_wrist",
    #"palm",
    # "ffproximal",
    # "ffmiddle",
    # "ffdistal",
    # "mfproximal",
    # "mfmiddle",
    # "mfdistal",
    # "rfproximal",
    # "rfmiddle",
    # "rfdistal",
    # "lfmetacarpal",
    # "lfproximal",
    # "lfmiddle",
    # "lfdistal",
    # "thproximal",
    # "thmiddle",
    # "thdistal",
    ]
    collision_spheres: 'spheres/bimanual_srhand_ur.yml'
    collision_sphere_buffer: 0.0
    self_collision_ignore: {
      "ra_upper_arm_link": ["ra_forearm_link", "ra_shoulder_link"],
      "ra_forarm_link": ["ra_wrist_1_link"],
      "ra_wrist_1_link": ["ra_wrist_2_link","ra_wrist_3_link"],
      "ra_wrist_2_link": ["ra_wrist_3_link",],
      "ra_wrist_3_link": ["rh_forearm"],
      
      # "forearm": ["wrist"],
      # "wrist": ["forearm"],

      "rh_forearm": ["rh_wrist","rh_palm"],
      "rh_wrist": ["rh_forearm","rh_palm"],
      #"palm": ["wrist"], # ,"ffproximal","mfproximal","rfproximal","lfmetacarpal","thproximal"],
      # "lfmetacarpal": ["palm","lfproximal"],

      # "thproximal": ["paml","thmiddle"],
          
      # "ffproximal": ["palm","ffmiddle"],
      # "mfproximal": ["palm","mfmiddle"],
      # "rfproximal": ["palm","rfmiddle"],
      # "lfproximal": ["lfmetacarpal","lfmiddle"],
          
      # "thmiddle": ["thproximal","thdistal"],
      # "ffmiddle": ["ffproximal","ffdistal"],
      # "mfmiddle": ["mfproximal","mfdistal"],
      # "rfmiddle": ["rfproximal","rfdistal"],
      # "lfmiddle": ["lfproximal","lfdistal"],
          
      # "thdistal": ["thmiddle"],
      # "ffdistal": ["ffmiddle"],
      # "mfdistal": ["mfmiddle"],
      # "rfdistal": ["rfmiddle"],
      # "lfdistal": ["lfmiddle"],
      }
    self_collision_buffer: {
      'ra_shoulder_link': 0.07,
      'ra_upper_arm_link': 0, 
      'ra_forearm_link': 0, 
      'ra_wrist_1_link': 0, 
      'ra_wrist_2_link': 0,
      'ra_wrist_3_link' : 0, 

      "rh_forearm": 0.0,
      "rh_wrist": 0.0,
      #"palm": 0.0,
      # "ffproximal": 0.0,
      # "ffmiddle": 0.0,
      # "ffdistal": 0.0,
      # "mfproximal": 0.0,
      # "mfmiddle": 0.0,
      # "mfdistal": 0.0,
      # "rfproximal": 0.0,
      # "rfmiddle": 0.0,
      # "rfdistal": 0.0,
      # "lfmetacarpal": 0.0,
      # "lfproximal": 0.0,
      # "lfmiddle": 0.0,
      # "lfdistal": 0.0,
      # "thproximal": 0.0,
      # "thmiddle": 0.0,
      # "thdistal": 0.0,
    }
    #mesh_link_names: [ 'shoulder_link','upper_arm_link', 'forearm_link', 'wrist_1_link', 'wrist_2_link' ,'wrist_3_link' ]
    lock_joints: null
    # {
    #   'WRJ2': 0.0, 'WRJ1': 0.0,
    #   'THJ5': 0.0, 'THJ4': 0.0, 'THJ3': 0.0, 'THJ2': 0.0, 'THJ1': 0.0,
    #   'LFJ5': 0.0, 'LFJ4': 0.0, 'LFJ3': 0.0, 'LFJ2': 0.0, 'LFJ1': 0.0,
    #   'RFJ4': 0.0, 'RFJ3': 0.0, 'RFJ2': 0.0, 'RFJ1': 0.0,
    #   'MFJ4': 0.0, 'MFJ3': 0.0, 'MFJ2': 0.0, 'MFJ1': 0.0,
    #   'FFJ4': 0.0, 'FFJ3': 0.0, 'FFJ2': 0.0, 'FFJ1': 0.0
    # }

    cspace:
      joint_names: ['ra_shoulder_pan_joint', 'ra_shoulder_lift_joint', 'ra_elbow_joint', 'ra_wrist_1_joint', 'ra_wrist_2_joint', 'ra_wrist_3_joint',
      'la_shoulder_pan_joint', 'la_shoulder_lift_joint', 'la_elbow_joint', 'la_wrist_1_joint', 'la_wrist_2_joint', 'la_wrist_3_joint',]
      
      retract_config: [0.0004430418193805963, -1.6971481482135218, 2.4696645736694336, -0.6649912039386194, 1.6591527462005615, 3.154633487910032272,
      0.0004430418193805963, -1.6971481482135218, 2.4696645736694336, -0.6649912039386194, 1.6591527462005615, 3.154633487910032272,]

      null_space_weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
      1.0, 1.0, 1.0, 1.0, 1.0, 1.0,]

      cspace_distance_weight: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0,
      1.0, 1.0, 1.0, 1.0, 1.0, 1.0,]

      max_jerk: 500.0
      max_acceleration: 12.0
      position_limit_clip: 0.1
      # add velocity scaling
      # add joint position limit clipping
