##
## Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
##
## NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
## property and proprietary rights in and to this material, related
## documentation and any modifications thereto. Any use, reproduction,
## disclosure or distribution of this material and related documentation
## without an express license agreement from NVIDIA CORPORATION or
## its affiliates is strictly prohibited.
##
robot: 'UR10_SHADOWHAND'
collision_spheres:
  ra_shoulder_link:
    - center: [0, 0, 0]
      radius: 0.05
    #- center: [0, 0, -0.18]
    #  radius: 0.09
  ra_upper_arm_link:
    - center: [-0, -0, 0.18]
      radius: 0.09
    - center: [-0.102167, 0,  0.18]
      radius: 0.05
    - center: [-0.204333, 0, 0.18]
      radius: 0.05
    - center: [-0.3065, 0, 0.18]
      radius: 0.05
    - center: [-0.408667, 0, 0.18]
      radius: 0.05
    - center: [-0.510833, 0, 0.18]
      radius: 0.05
    - center: [ -0.613, 0,0.18]
      radius: 0.07
  ra_forearm_link:
    - center: [-0, 0, 0.03]
      radius: 0.05
    - center: [-0.0951667, 0, 0.03]
      radius: 0.05
    - center: [-0.190333, 0, 0.03]
      radius: 0.05
    - center: [-0.2855, 0, 0.03]
      radius: 0.05
    - center: [-0.380667, 0,0.03]
      radius: 0.05
    - center: [-0.475833, 0,0.03]
      radius: 0.05
    - center: [-0.571, -1.19904e-17, 0.03]
      radius: 0.05
  ra_wrist_1_link:
    - center: [0, 0, 0]
      radius: 0.05
  ra_wrist_2_link:
    - center: [0, 0, 0]
      radius: 0.05
  ra_wrist_3_link:
    - center: [0, 0, 0]
      radius: 0.05
    - center: [0, 0, 0.06]
      radius: 0.07
  ra_tool0:
    - center: [0, 0, 0.12]
      radius: 0.05
  ra_camera_mount:
    - center: [0, 0.11, -0.01]
      radius: 0.06

  rh_forearm:
    # - "center": [0.0, 0.0, 0.0]
    #   "radius": 0.08
    # - "center": [0.0, 0.0, 0.14]
    #   "radius": 0.08
    # - "center": [0.0, 0.0, 0.047]
    #   "radius": 0.08
    - "center": [0.0, 0.0, 0.093]
      "radius": 0.01
  rh_wrist:
    - "center": [0.0, 0.0, 0.01]
      "radius": 0.035
  rh_palm:
    - "center": [-0.026, 0.0, 0.0]
      "radius": 0.012
    - "center": [-0.026, 0.0, 0.03]
      "radius": 0.012
    - "center": [-0.027, 0.0, 0.01]
      "radius": 0.012
    - "center": [-0.028, 0.0, 0.02]
      "radius": 0.012
    - "center": [0.033, 0.0, 0.0]
      "radius": 0.012
    - "center": [-0.015, 0.0, 0.0]
      "radius": 0.012
    - "center": [-0.004, 0.0, 0.0]
      "radius": 0.012
    - "center": [0.008, 0.0, 0.0]
      "radius": 0.012
    - "center": [0.019, 0.0, 0.0]
      "radius": 0.012
    - "center": [-0.01, 0.0, 0.09]
      "radius": 0.012
    - "center": [-0.01, 0.0, 0.015]
      "radius": 0.012
    - "center": [-0.01, 0.0, 0.03]
      "radius": 0.012
    - "center": [-0.01, 0.0, 0.045]
      "radius": 0.012
    - "center": [-0.01, 0.0, 0.06]
      "radius": 0.012
    - "center": [-0.01, 0.0, 0.075]
      "radius": 0.012
    - "center": [0.01, 0.0, 0.095]
      "radius": 0.012
    - "center": [0.008, -0.002, 0.016]
      "radius": 0.014
    - "center": [0.008, 0.0, 0.032]
      "radius": 0.012
    - "center": [0.009, 0.0, 0.048]
      "radius": 0.012
    - "center": [0.009, 0.0, 0.063]
      "radius": 0.012
    - "center": [0.01, 0.0, 0.079]
      "radius": 0.012
    - "center": [-0.001, 0.0, 0.023]
      "radius": 0.012
    - "center": [-0.001, 0.0, 0.039]
      "radius": 0.012
    - "center": [-0.001, 0.0, 0.054]
      "radius": 0.012
    - "center": [0.0, 0.0, 0.07]
      "radius": 0.012
    - "center": [0.033, 0.0, 0.09]
      "radius": 0.012
    - "center": [0.033, -0.003, 0.015]
      "radius": 0.014
    - "center": [0.033, 0.0, 0.03]
      "radius": 0.012
    - "center": [0.033, 0.0, 0.045]
      "radius": 0.012
    - "center": [0.033, 0.0, 0.06]
      "radius": 0.012
    - "center": [0.033, 0.0, 0.075]
      "radius": 0.012
    - "center": [0.021, 0.0, 0.069]
      "radius": 0.012
    - "center": [0.02, 0.0, 0.054]
      "radius": 0.012
    - "center": [0.02, 0.0, 0.038]
      "radius": 0.012
    - "center": [0.019, -0.003, 0.023]
      "radius": 0.015
    - "center": [0.02, -0.002, 0.008]
      "radius": 0.016
  rh_ffproximal:
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.01
    - "center": [0.0, 0.0, 0.04]
      "radius": 0.009
    - "center": [0.0, 0.0, 0.011]
      "radius": 0.01
    - "center": [0.0, 0.0, 0.021]
      "radius": 0.01
    - "center": [0.0, 0.0, 0.031]
      "radius": 0.009
  rh_ffmiddle:
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.009
    - "center": [0.0, 0.0, 0.025]
      "radius": 0.008
    - "center": [0.0, 0.0, 0.009]
      "radius": 0.009
    - "center": [0.0, 0.0, 0.017]
      "radius": 0.008
  rh_ffdistal:
    - "center": [0.0, 0.0, 0.013]
      "radius": 0.008
    - "center": [0.0, 0.0, 0.022]
      "radius": 0.007
  rh_mfproximal:
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.01
    - "center": [0.0, 0.0, 0.043]
      "radius": 0.009
    - "center": [0.0, 0.0, 0.011]
      "radius": 0.01
    - "center": [0.0, 0.0, 0.022]
      "radius": 0.01
    - "center": [0.0, 0.0, 0.033]
      "radius": 0.009
  rh_rfproximal:
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.01
    - "center": [0.0, 0.0, 0.04]
      "radius": 0.009
    - "center": [0.0, 0.0, 0.011]
      "radius": 0.01
    - "center": [0.0, 0.0, 0.021]
      "radius": 0.01
    - "center": [0.0, 0.0, 0.031]
      "radius": 0.009
  rh_rfmiddle:
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.009
    - "center": [0.0, 0.0, 0.025]
      "radius": 0.008
    - "center": [0.0, 0.0, 0.009]
      "radius": 0.009
    - "center": [0.0, 0.0, 0.017]
      "radius": 0.008
  rh_rfdistal:
    - "center": [0.0, 0.0, 0.013]
      "radius": 0.008
    - "center": [0.0, 0.0, 0.022]
      "radius": 0.007
  rh_mfmiddle:
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.009
    - "center": [0.0, 0.0, 0.025]
      "radius": 0.008
    - "center": [0.0, 0.0, 0.009]
      "radius": 0.009
    - "center": [0.0, 0.0, 0.017]
      "radius": 0.008
  rh_mfdistal:
    - "center": [0.0, 0.0, 0.01]
      "radius": 0.008
    - "center": [0.0, 0.0, 0.02]
      "radius": 0.007
  rh_lfmetacarpal:
    - "center": [0.05, 0.0, 0.035]
      "radius": 0.01
    - "center": [0.008, 0.0, 0.006]
      "radius": 0.01
    - "center": [0.017, 0.0, 0.012]
      "radius": 0.01
    - "center": [0.025, 0.0, 0.018]
      "radius": 0.01
    - "center": [0.033, 0.0, 0.023]
      "radius": 0.01
    - "center": [0.042, 0.0, 0.029]
      "radius": 0.01
  rh_lfproximal:
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.01
    - "center": [0.0, 0.0, 0.04]
      "radius": 0.009
    - "center": [0.0, 0.0, 0.011]
      "radius": 0.01
    - "center": [0.0, 0.0, 0.021]
      "radius": 0.01
    - "center": [0.0, 0.0, 0.031]
      "radius": 0.009
  rh_lfmiddle:
    - "center": [0.0, 0.0, 0.0]
      "radius": 0.009
    - "center": [0.0, 0.0, 0.024]
      "radius": 0.008
    - "center": [0.0, 0.0, 0.008]
      "radius": 0.009
    - "center": [0.0, 0.0, 0.016]
      "radius": 0.008
  rh_lfdistal:
    - "center": [0.0, 0.0, 0.007]
      "radius": 0.008
    - "center": [0.0, 0.0, 0.022]
      "radius": 0.007
    - "center": [0.0, 0.0, 0.015]
      "radius": 0.007
  rh_thproximal:
    - "center": [0.0, 0.0, 0.035]
      "radius": 0.01
    - "center": [0.0, 0.0, 0.024]
      "radius": 0.011
  rh_thmiddle:
    - "center": [0.0, 0.0, 0.035]
      "radius": 0.01
    - "center": [0.0, 0.0, 0.009]
      "radius": 0.01
    - "center": [0.0, 0.0, 0.018]
      "radius": 0.01
    - "center": [0.0, 0.0, 0.027]
      "radius": 0.01
  rh_thdistal:
    - "center": [0.0, 0.0, 0.015]
      "radius": 0.01
    - "center": [0.0, 0.0, 0.025]
      "radius": 0.009